spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ""
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
    username: sa
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      mode: always
      data-locations: classpath:/data.sql

logging:
  level:
    io.github.llh4github.simpleauth: debug

simple-auth:
  anno-url:
    - /authenticate/login